name: Secret Example

on: push

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: chekkout code
        uses: actions/checkout@v4
      - name: use the secret
        run: echo "calling API using secret"
      - name: secret length
        run: echo ${#MY_API_KEY}
        env:
          MY_API_KEY : ${{ secrets.API_KEY }}
        
